### ISSUE TITLE
item34 "其中第四个形参了音量" 应该为 "其中第四个形参指定了音量"

### ISSUE THREAD

**Issue by czhWellOptimized** [kelthuzadx/EffectiveModernCppChinese#112]
item34 "其中第四个形参了音量" 应该为 "其中第四个形参指定了音量"

**Comment by kelthuzadx** [comment]
感谢指出，[已修复](https://github.com/kelthuzadx/EffectiveModernCppChinese/commit/2c034e9d97a0acbd73ab1fb0eb130a7d2f0b8ef0)
