### ISSUE TITLE
关于一段话的请教

### ISSUE THREAD

**Issue by zmx19951103** [kelthuzadx/EffectiveModernCppChinese#38]
![image](https://user-images.githubusercontent.com/17705473/89101389-01b03580-d432-11ea-8dc9-ff62a1a247bc.png)
这里想请教一下，ParamType不是通用引用类型吗，是原版这样说的，还是后来加上的。在第一个item里面的一段文字

**Comment by kelthuzadx** [comment]
![image](https://user-images.githubusercontent.com/5010047/89101664-9451d400-d434-11ea-9493-d03a51e93c09.png)

原文是这样的

**Comment by zmx19951103** [comment]
嗯，感觉翻译成 “以右值引用类型的语法来声明” 也差不多一个意思。
