### ISSUE TITLE
Chapter 5：Item29.md

### ISSUE THREAD

**Issue by jiangwenhan** [kelthuzadx/EffectiveModernCppChinese#40]
The first letter should not be capital. The sequence of files in chapter 5 is incorrect. 🙃

**Comment by kelthuzadx** [comment]
目前我没有时间，如果您感兴趣或者其他贡献者感兴趣，欢迎对这部分进行修正。

**Comment by Leegoudan** [comment]
"另一方面，std::strnig提供了常数时间" == 应该是笔误：string
