### ISSUE TITLE
item 11中有句话没翻译

### ISSUE THREAD

**Issue by cellspace** [kelthuzadx/EffectiveModernCppChinese#69]
"This chapter is largely devoted to common practices in C++98 that have been superseded by better practices in C++11."

这句话两种翻译：
1.本节主要致力于讨论C ++ 98中的常见实践，这些实践已被C ++ 11中的更好的实践所取代。
2.本节主要致力于讨论C++98被C++11中更好的实践所取代的那些常见实践。

那种更好呢？个人感觉delete这节应该主要讨论的是C++11的东西，如果采用翻译1，则感觉像是在讨论C++98。

**Comment by kelthuzadx** [comment]
个人倾向于：

__本节主要致力于讨论C++98中那些被C++11所取代的最佳实践__

**Comment by cellspace** [comment]
> 个人倾向于：
> 
> **本节主要致力于讨论C++98中那些被C++11所取代的最佳实践**

好的，就按你这句翻译吧。感觉这句只是过渡的一句话，通顺更重要。
