### ISSUE TITLE
条款二十一中第三段的加粗错误

### ISSUE THREAD

**Issue by kongjun18** [kelthuzadx/EffectiveModernCppChinese#81]
> std::make_unique和std::make_shared是三个**make函数**中的两个：接收任意的多参数集合，完美转发到构造函数去动态分配一个对象，然后返回这个指向这个对象的指针。第三个make函数是std::allocate_shared。它行为和std::make_shared一样，只不过第一个参数是用来动态分配内存的allocator对象。

其中"`make`函数"被显示为\*\*`make`函数\*\*，没有加粗。

**Comment by kelthuzadx** [comment]
已修正
