### ISSUE TITLE
条款17 有错误

### ISSUE THREAD

**Issue by konglhui** [kelthuzadx/EffectiveModernCppChinese#85]
条款17  请记住 第三条  拷贝构造函数仅当类没有显式声明拷贝构造函数时才自动生成，并且如果用户声明了移动操作，拷贝构造就是delete。拷贝赋值运算符仅当类没有显式声明拷贝赋值运算符时才自动生成，并且如果用户声明了移动操作，拷贝赋值运算符就是delete。当用户声明了析构函数，拷贝操作的自动生成已被废弃。

最后一句，当用户声明了析构函数，拷贝操作的自动生成已被废弃。

拷贝操作是不是应该改为移动操作。

**Comment by kelthuzadx** [comment]
建议提PR进行修改：）

**Comment by konglhui** [comment]
我研究了一下，好像是我的理解有问题
