### ISSUE TITLE
chapter1: item3  "在这种形式下auto不再进⾏auto类型推导"

### ISSUE THREAD

**Issue by standback** [kelthuzadx/EffectiveModernCppChinese#96]
原文：
![image](https://user-images.githubusercontent.com/920696/127954163-7e6c1441-1587-45ee-9ac3-8a21157931f2.png)
译文：
![image](https://user-images.githubusercontent.com/920696/127954253-5f7e3dca-b1d1-41cd-ad28-3b6ab322d045.png)

这里的翻译好像是错的。

原文的意思应该是 
使用了这种声明形式， auto是要使用类型推导规则去推导他的类型的。更准确的说是编译器会从函数的实现去推导出函数的返回类型。

{简单的说就是， auto 是要使用函数 的实现，通过类型推导规则推导出函数的返回类型}

而译文，给出了相返的意思。“不推导类型”，应该是错误 的，

**Comment by kelthuzadx** [comment]
是的，确实是翻译错误。感谢指出。
